-- AlterTable
ALTER TABLE `Post` ADD COLUMN `origin` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `target` VARCHAR(255) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `Prompt` ADD COLUMN `origin` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `target` VARCHAR(255) NOT NULL DEFAULT '';
